USE it202_k25_ss2; 

CREATE TABLE users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(255) NOT NULL, 
    phone INT,
    email VARCHAR(255) UNIQUE, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- C1: Dùng ALER TABLE MODIFY ĐỂ THAY THAY INT THÀNH PHONE SAU ĐÓ DÙNG UPDATE ĐỂ THÊM SỐ 0 VÀO ĐẦU -> APP SẼ BỊ TREO 1 TÍ
ALTER TABLE users 
MODIFY phone VARCHAR(15) NOT NULL UNIQUE;
-- UPDATE EM CHƯA HỌC NÀO HỌC RỒI THÌ EM CHỈNH SAU Ạ 
 
-- C2: THÊM 1 CỘT MỚI CHUYỂN DỮ LIỆU QUA RỒI CŨNG DÙNG CHECK ĐỂ THÊM 0 VÀO ĐẦU SAU KHI ỔN ĐỊNH THÌ XÓA CỘT CŨ 
-- -> APP VẪN CHẠY BÌNH THƯỜNG => DÙNG C1 VÌ ĐẰNG NÀO NGƯỜI DÙNG CŨNG CÓ ĐĂNG NHẬP ĐƯỢC ĐÂU.. 